In [1]:
import numpy as np

# 1. NumPy array with values 1 to 10
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1.", arr1)



1. [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# 2. Array of zeros with shape (3,3)
arr2 = np.zeros((3, 3))
print("2.\n", arr2)


2.
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# 3. Array of ones with shape (2,4)
arr3 = np.ones((2, 4))
print("3.\n", arr3)


3.
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# 4. Shape and size of an array
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print("4. Shape:", arr4.shape, "| Size:", arr4.size)

4. Shape: (2, 3) | Size: 6


In [15]:
# 5. arange() from 1 to 20 with step 2
arr5 = np.arange(1, 20, 2)
print("5.", arr5)


5. [ 1  3  5  7  9 11 13 15 17 19]


In [16]:
# 6. Reshape 1D array into 2x3 matrix
arr6 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print("6.\n", arr6)

6.
 [[1 2 3]
 [4 5 6]]


In [17]:
# 7. Sum of all elements
arr7 = np.array([10, 20, 30, 40, 50])
print("7. Sum:", np.sum(arr7))


7. Sum: 150


In [18]:
# 8. Maximum and minimum values
arr8 = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("8. Max:", np.max(arr8), "| Min:", np.min(arr8))

8. Max: 9 | Min: 1


In [34]:


# 9. Sort elements
arr9 = np.array([5, 2, 8, 1, 9, 3])
print("9. Sorted:", np.sort(arr9))



9. Sorted: [1 2 3 5 8 9]


In [35]:
# 10. 5 random integers between 1 and 50
arr10 = np.random.randint(1, 51, size=5)
print("10.", arr10)

10. [33  3 24 27 44]


In [33]:
# NumPy_Assignment_<RollNo>.py
import numpy as np

# ============================================================
# SECTION A: CORE ARRAY OPERATIONS & FOUNDATIONS
# ============================================================

# Q1. Create a 1D NumPy array from a Python list
arr1 = np.array([1, 2, 3, 4])
print("Q1. 1D Array:", arr1)



Q1. 1D Array: [1 2 3 4]


In [2]:
# Q2. 4x4 array of zeros
arr2 = np.zeros((4, 4))
print("\nQ2. 4x4 Zeros:\n", arr2)


Q2. 4x4 Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Q3. 3x5 array of ones
arr3 = np.ones((3, 5))
print("\nQ3. 3x5 Ones:\n", arr3)


Q3. 3x5 Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
# Q4. 5x5 Identity Matrix
arr4 = np.eye(5)
print("\nQ4. 5x5 Identity Matrix:\n", arr4)



Q4. 5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# Q5. Array from 10 to 50 with step 5
arr5 = np.arange(10, 51, 5)
print("\nQ5. arange(10, 51, 5):", arr5)



Q5. arange(10, 51, 5): [10 15 20 25 30 35 40 45 50]


In [7]:
# Q6. 10 evenly spaced numbers from 1 to 100
arr6 = np.linspace(1, 100, 10)
print("\nQ6. linspace(1, 100, 10):", arr6)


Q6. linspace(1, 100, 10): [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [8]:
# Q7. Shape of an array
arr7 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nQ7. Shape:", arr7.shape)



Q7. Shape: (2, 3)


In [9]:
# Q8. Size (total elements) of an array
print("\nQ8. Size:", arr7.size)


Q8. Size: 6


In [10]:
# Q9. Number of dimensions (ndim)
print("\nQ9. ndim:", arr7.ndim)


Q9. ndim: 2


In [11]:
# Q10. Reshape 1D (12 elements) into 3x4
arr10 = np.arange(1, 13).reshape(3, 4)
print("\nQ10. Reshaped 3x4:\n", arr10)


Q10. Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# Q11. Flatten 2D array to 1D
arr11 = arr10.flatten()
print("\nQ11. Flattened:", arr11)



Q11. Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# Q12. Max, Min, Mean
arr12 = np.array([15, 42, 7, 93, 26, 61, 38])
print("\nQ12. Max:", arr12.max(), "| Min:", arr12.min(), "| Mean:", arr12.mean())



Q12. Max: 93 | Min: 7 | Mean: 40.285714285714285


In [14]:
# Q13. Row-wise and Column-wise sum
arr13 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\nQ13. Column-wise sum (axis=0):", arr13.sum(axis=0))
print("     Row-wise sum    (axis=1):", arr13.sum(axis=1))


Q13. Column-wise sum (axis=0): [12 15 18]
     Row-wise sum    (axis=1): [ 6 15 24]


In [15]:
# Q14. Sort array in ascending order
arr14 = np.array([40, 10, 70, 30, 90, 20])
print("\nQ14. Sorted:", np.sort(arr14))


Q14. Sorted: [10 20 30 40 70 90]


In [16]:
# Q15. Index of maximum value (argmax)
arr15 = np.array([5, 23, 11, 67, 34, 89, 42])
print("\nQ15. Index of Max value:", np.argmax(arr15))


Q15. Index of Max value: 5


In [17]:
# Q16. Index of minimum value (argmin)
print("\nQ16. Index of Min value:", np.argmin(arr15))


Q16. Index of Min value: 0


In [18]:
# Q17. Element-wise addition, subtraction, multiplication
a = np.array([10, 20, 30, 40])
b = np.array([5,  10, 15, 20])
print("\nQ17. Addition      :", a + b)
print("     Subtraction   :", a - b)
print("     Multiplication:", a * b)


Q17. Addition      : [15 30 45 60]
     Subtraction   : [ 5 10 15 20]
     Multiplication: [ 50 200 450 800]


In [19]:
# Q18. Dot product / Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("\nQ18. Dot Product:\n", np.dot(mat1, mat2))
print("     Using @:\n",       mat1 @ mat2)



Q18. Dot Product:
 [[19 22]
 [43 50]]
     Using @:
 [[19 22]
 [43 50]]


In [20]:
# Q19. Random integers between 1 and 100
arr19 = np.random.randint(1, 101, size=8)
print("\nQ19. Random Integers:", arr19)


Q19. Random Integers: [22 61 12 72 63 23  3 43]


In [21]:
# Q20. Unique values from array with duplicates
arr20 = np.array([10, 30, 20, 10, 50, 30, 40, 20, 50])
print("\nQ20. Unique Values:", np.unique(arr20))


Q20. Unique Values: [10 20 30 40 50]


In [22]:
# ============================================================
# SECTION B: ADVANCED MATRICES & LOGICAL MANIPULATIONS
# ============================================================

# Q21. Vertical stack (vstack)
v1 = np.array([[1, 2, 3], [4, 5, 6]])
v2 = np.array([[7, 8, 9]])
print("\nQ21. vstack:\n", np.vstack((v1, v2)))



Q21. vstack:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Q22. Horizontal stack (hstack)
h1 = np.array([[1, 2], [3, 4]])
h2 = np.array([[5, 6], [7, 8]])
print("\nQ22. hstack:\n", np.hstack((h1, h2)))


Q22. hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [25]:
# Q23. Split array into sub-arrays
arr23 = np.arange(1, 13)
split_arr = np.split(arr23, 4)
print("\nQ23. Split into 4 parts:", split_arr)


Q23. Split into 4 parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [26]:
# Q24. Transpose of a matrix
arr24 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("\nQ24. Original:\n", arr24)
print("     Transpose:\n", arr24.T)



Q24. Original:
 [[1 2 3]
 [4 5 6]]
     Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [27]:
# Q25. Diagonal elements of a matrix
arr25 = np.array([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9,  10, 11, 12],
                  [13, 14, 15, 16]])
print("\nQ25. Diagonal Elements:", np.diag(arr25))


Q25. Diagonal Elements: [ 1  6 11 16]


In [28]:
# Q26. Boolean mask for elements > 50
arr26 = np.array([23, 55, 10, 78, 45, 91, 34, 62])
mask = arr26 > 50
print("\nQ26. Boolean Mask (> 50):", mask)
print("     Elements > 50:", arr26[mask])


Q26. Boolean Mask (> 50): [False  True False  True False  True False  True]
     Elements > 50: [55 78 91 62]


In [29]:
# Q27. Replace elements > 50 with 0
arr27 = arr26.copy()
arr27[arr27 > 50] = 0
print("\nQ27. After replacing >50 with 0:", arr27)


Q27. After replacing >50 with 0: [23  0 10  0 45  0 34  0]


In [30]:
# Q28. Cumulative Sum
arr28 = np.array([1, 2, 3, 4, 5])
print("\nQ28. Cumulative Sum:", np.cumsum(arr28))



Q28. Cumulative Sum: [ 1  3  6 10 15]


In [31]:
# Q29. Cumulative Product
arr29 = np.array([1, 2, 3, 4, 5])
print("\nQ29. Cumulative Product:", np.cumprod(arr29))



Q29. Cumulative Product: [  1   2   6  24 120]


In [32]:
# Q30. Random float array between 0.0 and 1.0
arr30 = np.random.rand(3, 4)
print("\nQ30. Random Float Array (3x4):\n", arr30)


Q30. Random Float Array (3x4):
 [[0.89633887 0.5448316  0.18383906 0.59327509]
 [0.66302285 0.21966908 0.30758079 0.78495449]
 [0.68001145 0.62304479 0.90789371 0.28894892]]
